#!/bin/bash

ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/tmux.conf ~/.tmux.conf
ln -sf $PWD/tmux.conf.local ~/.tmux.conf.local
ln -sf $PWD/tmux.conf.local.user ~/.tmux.conf.local.user
ln -sf $PWD/myenv.sh ~/bin/myenv.sh
ln -sf $PWD/myfunc.sh ~/bin/myfunc.sh
